config/urls.py
import json
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views import defaults as default_views

# Read quotes as an array to send
quotes = json.load(open(str(settings.QUOTES_PATH)))
# Pass to the base view
def base_view(request):
    """ Default view for the root """
    return render(request, 'pages/home.html', {'quotes': json.dumps(quotes)})

urlpatterns = [
    url(r'^$', base_view, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

mgscott/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

mgscott/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

mgscott/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

mgscott/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

mgscott/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Michael Bot Paper Company{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <!-- Your stuff: Third-party CSS libraries go here -->
    <link href="https://fonts.googleapis.com/css?family=Special+Elite" rel="stylesheet">

    <!-- This file stores project-specific CSS -->    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

    {% block google_analytics %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-115999842-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-115999842-1');
    </script>
    {% endblock %}

  </head>

  <body>

    <div class="d-flex flex-column justify-content-between" id="michaelContainer">
      <div class="pt-3 pb-1 text-center" id="title">
          <h1>Michael Bot Paper Company*</h1>
      </div>
      <div class="pt-1 mx-auto text-center" id="subtitle">
        <div class="row">
          <div class="col py-1 my-auto">
            <div class="row">
              <div class="col-12 col-sm-auto mx-auto pr-1">
                <p>
                  <b>(</b>
                  <code>Machine learning</code>
                  <i class="fa fa-plus"></i>
                </p>
              </div>
              <div class="col-12 col-sm-auto mx-auto px-0">
                <p>
                  Michael Scott
                  <b>)</b>
                </p>
              </div>
              <div class="col-12 col-sm-auto mx-auto pl-1">
                <i class="fa fa-arrow-right"></i>
                <i class="wisdom">Infinite Wisdom.</i>
              </div>
            </div>
          </div>
          <div class="col-12 col-sm-auto py-1">
            <button class="btn btn-sm" data-toggle="modal" data-target="#infoModal" type="button">(more info)</button>
          </div>
      </div>
      </div>
      
      <div class="col-12 col-md-10 pt-3 pb-1 mx-auto text-justify" id="quote">
        <h2 id="quoteText"></h2>
      </div>
      <div class="p-1 mx-auto" id="next-button">
        <button class="btn btn-lg" id="newQuote" type="button">Another insight? Yes please.</button>
      </div>
      <div class="p-1 mx-auto" id="frame">
        <img class="img-fluid" id="michaelPic" src="{% static 'images/mscott1.jpeg' %}">
      </div>

      <div class="py-3 my-3 mx-0 text-center" id="email-box">
        <div class="row mx-auto">
          <div class="col" id="email-box-text">
            <h5>Want Michael Scott ML-Generated wisdom sent to your inbox? Enter your email here.</h5>
          </div>
        </div>
        <div class="row mx-auto">
          <div class="col mx-auto input-group" id="email-box-input">
            <!-- Begin MailChimp Signup Form -->
            <link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
            <div id="mc_embed_signup">
              <form action="https://stolson.us12.list-manage.com/subscribe/post?u=16252f84849cbd6dab3bc02a3&amp;id=de707c52e0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                <div id="mc_embed_signup_scroll">
                  <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="holly@dundermifflin.sabre" required>
                  <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                  <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_16252f84849cbd6dab3bc02a3_de707c52e0" tabindex="-1" value=""></div>
                  <div class="clear"><input type="submit" value="Sign Up" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>

      <div class="py-3 p-1 mx-auto" id="coffee-button">
        <a href="https://www.buymeacoffee.com/fQGd5AtCW" target="_blank"><img src="https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png" alt="Buy Me A Coffee" style="height: auto !important;width: auto !important;" ></a>
      </div>

      <div class="p-0 my-0 mx-auto d-flex justify-content-center" id="social">
        <div class="col-auto">
          <a href="http://www.twitter.com/st0lson"/><i class="fa fa-twitter"></i></a>
        </div>
        <div class="col-auto">
          <a href="http://www.github.com/stolson"/><i class="fa fa-github"></i></a>
        </div>
        <div class="col-auto">
          <a href="http://www.gitlab.com/stolson1"/><i class="fa fa-gitlab"></i></a>
        </div>
        <div class="col-auto">
          <a href="mailto:steve@stolson.com"/><i class="fa fa-envelope"></i></a>
        </div>
        <div class="col-auto">
          <a href="http://www.stolson.com"/><i class="fa fa-globe"></i></a>
        </div>
      </div>
      <div class="p-0 my-2 mx-auto text-center align-self-end" id="disclaimer">
        <div class="col">
            <p><small>*This site is not associated with NBC, NBCUniversal, or NBC's The Office. We're just fans.</small></p>
        </div>
      </div>
    </div>

    {% include 'pages/info-modal.html' %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
          
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      <script src="https://use.fontawesome.com/796efe771c.js"></script>

      <!-- place project specific Javascript in this file -->      
      <script src="{% static 'js/project.js' %}"></script>
      <script type="text/javascript">
        var quotes  = JSON.parse("{{ quotes | escapejs }}").quotes;
      </script>


    {% endblock javascript %}
  </body>
</html>
 

mgscott/templates/info-modal.html
{% block modal %}

<div class="modal fade contact-modal-lg" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h3 class="modal-title" id="contactModalLabel">Michael Scott and Machine Learning</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body text-left">
        <p>This site was inspired by the rumors of an Office reboot (I have no knowledge of whether or not that's true) and since his role has concluded, so we have to make his lines for him. I'm not much of a comedy writer, so I built this.</p>
        <br>
        <p>The processing under the hood is done with Natural Language Toolkit and Markov Chains with Backoff. Inspiration and some code is <b><a href="https://blog.dataiku.com/2016/10/08/machine-learning-markov-chains-generate-clinton-trump-quotes">here</a></b>. The source code of the site is <b><a href="https://www.gitlab.com/stolson1/mgscott">here</a></b>. Check the readme on how to generate your own quotes. I generated a lot and filtered them down to the ones I liked the most.</p>
        <br>
        <p>To keep updated on my new projects (maybe there will be a Dwight one!) you can add your email here. I promise no spam, no bullshit.</p>
        <div class="mx-auto py-3 input-group" id="email-box-input">
          <input type="text" class="form-control" placeholder="hi@stolson.com" aria-label="Username" aria-describedby="basic-addon1">
          <div class="input-group-append">
            <button class="btn btn-info" type="button">Sign Up</button>
          </div>
        </div>
        <p>You can reach me at <a href="stolson.com">stolson.com</a>. Keep in mind this is just a fan site. It's not affiliated in any way with the show or its affiliates.</p>
      </div>

    </div>
  </div>
</div>

{% endblock %}

mgscott/templates/pages/about.html
{% extends "base.html" %}

mgscott/templates/pages/home.html
{% extends "base.html" %}

mgscott/templates/pages/info-modal.html
{% block modal %}

<div class="modal fade contact-modal-lg" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h3 class="modal-title" id="contactModalLabel">Michael Scott and Machine Learning</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body text-left">
        <p>This site was inspired by the rumors of an Office reboot (I have no knowledge of whether or not that's true) and since his role has concluded, so we have to make his lines for him. I'm not much of a comedy writer, so I built this.</p>
        <br><br>
        <p>The processing under the hood is done with Natural Language Toolkit and Markov Chains with Backoff. Inspiration and some code is <b><a href="https://blog.dataiku.com/2016/10/08/machine-learning-markov-chains-generate-clinton-trump-quotes">here</a></b>. The source code of the site is <b><a href="https://www.gitlab.com/stolson1/mgscott">here</a></b>. Check the readme on how to generate your own quotes. I generated a lot and filtered them down to the ones I liked the most.</p>
        <br><hr><br>
        <p>To keep updated on my new projects (maybe there will be a Dwight one!) you can add your email here. I promise no spam, no bullshit.</p>
        <div class="mx-auto py-3 input-group" id="email-box-input">
          <!-- Begin MailChimp Signup Form -->
          <div id="mc_embed_signup">
            <form action="https://stolson.us12.list-manage.com/subscribe/post?u=16252f84849cbd6dab3bc02a3&amp;id=da46d91356" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                <div id="mc_embed_signup_scroll">
                  <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="hi@stolson.com" required>
                    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_16252f84849cbd6dab3bc02a3_da46d91356" tabindex="-1" value=""></div>
                    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
                </div>
            </form>
          </div>
          <!--End mc_embed_signup-->
        </div>
        <p>You can reach me at <a href="https://www.stolson.com">stolson.com</a>. Keep in mind this is just a fan site. It's not affiliated in any way with the show or its affiliates.</p>
      </div>

    </div>
  </div>
</div>

{% endblock %}

mgscott/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

mgscott/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

mgscott/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}